name: Docker Image CI

on:

  #是否展示手动点击按钮
  workflow_dispatch:
  # push 自动触发
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
          fail-fast: false
          matrix:
            platform:
              - linux/amd64
              - linux/arm64
              - linux/arm/v7
    steps:
    
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: xueyikang
        password: ${{ secrets.CREDENTIAL }}
      
    - name: Build and Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        file: ./Dockerfile
        tags: xueyikang/stealer
        platforms: linux/amd64,linux/arm64

    - name: Build and Push Docker arm image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        file: ./Dockerfile_ARM
        tags: xueyikang/stealer
        platform: linux/arm/v7